### ISSUE TITLE
Please upload document file

### ISSUE THREAD

**Issue by KevinXuxuxu** [rlbarter/modelfit#1]
Thx

**Comment by rlbarter** [comment]
Hey Kevin, 

In the vignettes folder you'll find Tutorial.html which is a tutorial document which shows how to use the package. I've also updated the README so that the relevant information is shown on the github page. If you've loaded the package into R and loaded the library into your workspace, you can also see all of the options for the two main functions by typing "?modelfit" and "?plot.modelfit". Is this helpful? Let me know if there was something else you'd like me to upload!

**Comment by KevinXuxuxu** [comment]
Splendid! That's very helpful! Thx!
![hey](http://imglf1.ph.126.net/HcMYd8Z1LAkKC4zjrionKQ==/6619523993119455985.png)
